version: '3'
services:
  jupyterlab:
    build:
      context: ..
      dockerfile: Dockerfile
      args: 
        - CLOUDVOLUME_TOKEN=${CLOUDVOLUME_TOKEN}
    volumes:
      - ../notebooks:/src/notebooks
    ports:
      - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT_CONTAINER:-8888}:8888"
    env_file:
      - .env
    container_name: python-practice-jupyterlab
    entrypoint: /src/python-practice/deploy/entrypoint.sh